export const Images = {
  plantApp: require('./onboardingflowerpot.png'),
  spray: require('./onboardingsprinkler.png'),
  sun: require('./onboardinglight.png'),
  water: require('./onboardingwater.png'),
  camera: require('./camera.png'),
  background: require('./background.png'),
  background2: require('./background2.png'),
  background3: require('./background3.png'),
  onboarding1phone: require('./onboardingphone.png'),
  onboarding1brush: require('./onboardingbrush.png'),
  onboarding2phone: require('./onboarding2phone.png'),
  onboarding2twopot: require('./onboarding2twopot.png'),
  scanner: require('./scanner.png'),
  speedmeter: require('./speedmeter.png'),
  leaf: require('./leaf.png'),
  messagebox: require('./messagebox.png'),
  tabbarscanner: require('./tabbarscanner.png'),
  backgroundmodal: require('./backgroundmodal.jpeg'),
};
